// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/callback": {
    params: {};
  };
  "/stream": {
    params: {};
  };
  "/actions/toggle-theme": {
    params: {};
  };
  "/actions/toggle-featured": {
    params: {};
  };
  "/api/:username": {
    params: {
      "username": string;
    };
  };
  "/api/:username/og": {
    params: {
      "username": string;
    };
  };
  "/:username": {
    params: {
      "username": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth/callback" | "/stream" | "/actions/toggle-theme" | "/actions/toggle-featured" | "/api/:username" | "/api/:username/og" | "/:username";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.callback.tsx": {
    id: "routes/auth.callback";
    page: "/auth/callback";
  };
  "routes/stream.tsx": {
    id: "routes/stream";
    page: "/stream";
  };
  "routes/actions.toggle-theme.tsx": {
    id: "routes/actions.toggle-theme";
    page: "/actions/toggle-theme";
  };
  "routes/actions.toggle-featured.tsx": {
    id: "routes/actions.toggle-featured";
    page: "/actions/toggle-featured";
  };
  "routes/api.$username.tsx": {
    id: "routes/api.$username";
    page: "/api/:username";
  };
  "routes/api.$username.og.tsx": {
    id: "routes/api.$username.og";
    page: "/api/:username/og";
  };
  "routes/$username.tsx": {
    id: "routes/$username";
    page: "/:username";
  };
};